AWSTemplateFormatVersion: "2010-09-09"
Description: "Shared DynamoDB table for Super Simple Apps Business Tools (CRM, Invoice, Job Timer)"

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (dev or prod)
    AllowedValues:
      - dev
      - prod

Resources:
  # Single table design for business app user data
  # This table is shared by: CRM, Invoice, Job Timer
  # (Flashcards has its own separate table)
  #
  # PK/SK patterns:
  #   USER#{userId}#CLIENT#{clientId} / METADATA - CRM clients
  #   USER#{userId}#INVOICE#{invoiceId} / METADATA - Invoices
  #   USER#{userId}#INVOICE#{invoiceId} / ITEM#{itemId} - Invoice line items
  #   USER#{userId}#JOB#{jobId} / METADATA - Job Timer jobs
  #   USER#{userId}#JOB#{jobId} / SESSION#{sessionId} - Timer sessions
  BusinessDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "super-simple-apps-business-${Stage}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        # GSI1: Query by user and type (e.g., all clients for a user)
        # GSI1PK: USER#{userId}#TYPE#{type} (e.g., USER#123#TYPE#CLIENT)
        # GSI1SK: CREATED#{timestamp} or NAME#{name} for sorting
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI2: For cross-references (e.g., invoices by client)
        # GSI2PK: CLIENT#{clientId} or JOB#{jobId}
        # GSI2SK: INVOICE#{invoiceId} or SESSION#{sessionId}
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: App
          Value: ssa-business
        - Key: Stage
          Value: !Ref Stage
        - Key: ManagedBy
          Value: cloudformation

Outputs:
  TableName:
    Description: Name of the business apps DynamoDB table
    Value: !Ref BusinessDataTable
    Export:
      Name: !Sub "SuperSimpleApps-BusinessTableName-${Stage}"

  TableArn:
    Description: ARN of the business apps DynamoDB table
    Value: !GetAtt BusinessDataTable.Arn
    Export:
      Name: !Sub "SuperSimpleApps-BusinessTableArn-${Stage}"
